import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { Header } from "@/components/shared/Header/Header";
import { Container } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<Container
							maxW="100%"
							minH="100vh"
							bg="purple.900"
							color="white"
						>
						<Container maxW="3xl">
							<Header />
						</Container>
						<Container maxW="3xl" centerContent>
							{children}
						</Container>
					</Container>
				</Providers>
			</body>
		</html>
	);
}
